project:
  type: website

website:
  title: "An Analysis of Power Plays in the NHL"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: https://github.com/anly501/dsan-5000-project-geh1221
        text: Code
      - href: https://github.com/anly501/dsan-5000-project-geh1221
        text: Data
      - href: introduction.ipynb
        text: Introduction
      - href: data-gathering.ipynb
        text: Data Gathering
      - href: data-cleaning.html
        text: Data Cleaning
      - href: exploratory_data_analysis.qmd
        text: Data Exploration
      - href: naive_bayes.html
        text: Naive Bayes
      - href: Clustering.html
        text: Clustering
      - href: dimensionality-reduction.html
        text: Dimensionality Reduction
      - href: decision-trees.html
        text: Decision Trees
      - href: conclusions.ipynb
        text: Conclusions

format:
  html:
    theme: cosmo
    toc: true



