---
title: Data Gathering
jupyter: python3
author: Grace Hyland
format:
  html:
    code-fold: true
editor: visual
---

### Overview

In this project, I use three different sets of data. These include data sets are the following:
1. Team data by season
2. Individual player data in 2022
3. Team records data

### Team Data by Season

The team data by season data comes from the website moneypuck.com which is one of the foremost hockey analytics websites. The website tracks live data from current games and the current season and also provides data on hockey betting, playoff odds, and league wide standings. The team data by season can be downloaded from the data tab on the website as a csv file.

The data is split into different files for each season. In this portfolio I use data going back five seasons to the 2018-2019 season. I excluded the dataset for the 2019-2020 season because it was cut short due to COVID and then continued at a later date in a different format.

The data includes five rows for each of the 32 NHL teams; one row for 5 on 5 play, one row for 5 on 4 play, one row for 4 on 5 play, one row for any other situation (such as 5 on 3, or 3 on 3 in overtime), and one row that includes data from all game situations. There are 100 variables measured so in the data cleaning process I will have to reduce these to the most relevant for my data science question.

### Individual Player Data

The individual player data from 2022 also came from the moneypuck.com website and can be downloaded as a csv file from the tab on the website. The data can be downloaded by season so I took data from the 2022-2023 season. For the individual player data I took data for only one season because there are far more observations of individual players in a season than the 32 NHL teams and there are slight rule changes and variations in the game across seasons so it is better to only compare within a season when possible.

Similar to the team data, there are 100 variables recorded which will have to be reduced in the data cleaning process.

### Team Record Data

The team record data comes from hockey-reference.com. hockey-reference.com contains traditional data on the NHL going back to the 1917-1918 season. The data available in the website includes data for teams and players by career and season as well as record holder data in many categories. The dataset I downloaded includes many traditional hockey statistics including league standing points, power play percentage, and power play goals for each team during the 2022-2023 season. In this portfolio, these three variables will be used from this dataset so other information will have to be removed during the data cleaning process.

